#!/bin/sh
set -x

#sudo mvn clean install -Pdocker-build-image -DskipTests
sudo mvn clean install -DskipTests

modules="eureka zuul core speed location oil"
./compile_module ${modules}

echo "=========================================================="
echo "=========================================================="
echo "Compile the modules : ${module}"
echo "=========================================================="
sudo docker images

