#!/bin/sh
set -x
sudo docker rm -f dg-imo-speed
sleep 2
sudo mvn clean install -Pdocker-build-image -DskipTests
sleep 2
#sudo docker run -it --name dg-imo-speed dg-imo-speed:latest

#sudo mvn clean install -Pdocker-push-image
#mvn -Ddocker.username=jkong85 -Ddocker.password=19851208 docker:push


sudo docker images | sed -n '2p'

